### ISSUE TITLE
Mean vs Median

### ISSUE THREAD

**Issue by agstn** [RhoInc/sas-violinPlot#1]
In my opinion you should be plotting and joining (red dots & lines) the medians and not the means because you are using quartiles as the main feature of the plot. The median will be more robust against departures of symmetry than the mean.

**Comment by samussiah** [comment]
Cool deal, I'll let the user choose what statistic the line connects.  Thanks Agustin!

**Comment by samussiah** [comment]
Trend line connects medians by default and additionally the user can choose which statistic the trend line connects.
